- frontend/index.html
- frontend/src/layouts/default/AppBar.vue
- 상단 타이틀을 영문에서 한글로 수정했다
- 프로젝트 페이지 타이틀을 슈룹으로 수정했다
> refactor: 상단 타이틀 영문에서 한글로 수정

- frontend/.eslintrc.js
- frontend/.prettierrc
- frontend/index.html
- frontend/jsconfig.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/plugins/index.js
- frontend/src/store/app.js
- frontend/src/store/index.js
- frontend/src/styles/global.style.css
- frontend/src/views/Home.vue
- frontend/vite.config.js
-prettier 세팅 및 파일 포맷
npm run format: prettier 설정에 맞춰 포맷화(필요할때만 하면 됩니다)
> Chore: prettier 세팅 및 포맷

- frontend/src/components/Footer.vue
- frontend/src/layouts/default/View.vue
> Refactor: footer,layout 여백을 조정한다

- frontend/src/components/Form/AgreementCheckBox.vue
- frontend/src/components/Form/AgreementDialog.vue
- frontend/src/components/Form/PhoneInput.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/components/Form/data/usageRules.js
- frontend/src/components/ProductCardMain.vue
- frontend/src/components/Title.vue
- frontend/src/consts/agree.js
- frontend/src/router/index.js
- frontend/src/views/Signup.vue
회원가입 페이지 UI를 구현했다
- 약관 내용 추후 정리 및 추가 필요
> Design: 회원가입 페이지 UI 구현

- backend/rule-config/naver-checkstyle-rules.xml
- backend/rule-config/naver-checkstyle-suppressions.xml
- backend/rule-config/naver-intellij-formatter.xml
네이버 백엔드 코드 컨벤션을 참고하여  
우리 프로젝트의 백엔드 코드 컨벤션을 설정했습니다.
intellij에 자동으로 컨벤션을 적용하는 방법이 있습니다.   
해동 설정 내용은 참고 사항에 있습니다.  
또한, checkstyle 플러그인을 통해 컨벤션에 맞는 코드인지 확인할 수 있다.  
- [intellij에 코드 컨벤션 적용하기](https://bestinu.tistory.com/64#article-1-2-1--1--checkstyle-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%B9%98)
> Chore: 백엔드 코드 컨벤션을 설정한다 

- backend/build.gradle
- backend/src/docs/asciidoc/auth.adoc
- backend/src/main/java/com/easypeach/shroop/infra/config/SecurityConfig.java
- backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
- backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
- backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/domain/SecurityMember.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignInRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignUpRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/AccessTokenResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/SignUpCompletedResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/exception/InvalidTokenException.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/global/exception/dto/ErrorResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
- 회원가입
- 로그인 시 JWT 발급 (AccessToken)
- DTO 유효성 검증 및 예외처리
추가적으로 처리하지 않은 아래 부분은 다른 이슈에서 진행하고자 합니다.
- 회원가입 예외처리 (중복 검사)
- Rest Docs 로 api 문서 작성 학습 필요
> Feat: JWT 기반 인증인가 구현 (회원가입,로그인)

- frontend/src/components/ProductCardMain.vue
- frontend/src/views/Home.vue
게시글 카드형의 내용을 수정했습니다.
위의 사진처럼 구현했습니다.
> Feat: 게시글 카드형 수정

- backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
네이버 클라우드 플랫폼 SMS API 시그니처 생성 메서드를 구현했습니다.
yml 파일 수정해주세요!
- [SMS 전송 API](https://born2bedeveloper.tistory.com/67)
> Feat:휴대폰 인증 시그니처 생성

- backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/support/LoginMember.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/support/LoginMemberId.java
- backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
LoginMember 애노테이션 작성
컨트롤러 메서드에 @LoginMember 사용시 로그인된 Member 값을 저장합니다
@LoginMemberId 사용시 로그인된 사용자의 Member ID가 저장됩니다. (테이블의 PK값)
> Feat: 로그인된 사용자의 정보를 참조하는 기능 구현

- frontend/src/components/ProductCardMain.vue
- frontend/src/views/Home.vue
좋아요 버튼의 테두리를 삭제했습니다.
이미지 안에 있는 글을 삭제하고 크기를 고정으로 수정했습니다.
그리고 이미지 클릭시 상품 상세페이지로 이동할 수 있도록 수정했습니다.
> Refactor: 게시글 카드형 수정한다

- frontend/src/router/index.js
router 경로를 변경 및 추가를 했습니다
lazy-load 옵션을 제거했습니다
[참고 - vue router lazy load](https://router.vuejs.org/guide/advanced/lazy-loading.html)
아직 개발 완료전인 페이지는 component import를 주석 처리했습니다
> Feature: router 경로 변경 및 lazy load 옵션을 제거한다

- frontend/src/views/Login.vue
form  태그와 submit handler를 추가 했습니다
> Refactor: form 태그와  submit handler를 추가했다

- frontend/src/layouts/default/AppBar.vue
Header에 회원가입 버튼을 추가했습니다
tooltips의 버튼 영역을 확장했다.
> Refactor: Header에 회원가입 버튼을 추가했다

- frontend/.eslintrc.js
- frontend/.prettierrc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/components/Form/PasswordInput.vue
- frontend/src/components/ProductTitle.vue
- frontend/src/main.js
- frontend/src/plugins/vuetify.js
Eslint/prettier 기준을 재설정하고 변경된 기준에 따라 Format을 다시 진행했다
pull 받은 후 아래 명령어 차례로 실행
- 1. npm install
- 2. npm run lint
- 3. npm run format
> Chore: eslint/prettier 재설정

- frontend/src/components/Alert/InfoAlert.vue
- frontend/src/components/Alert/WarnAlert.vue
- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/components/GuideText.vue
- frontend/src/components/ImageAttach.vue
- frontend/src/components/ProductTitle.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/router/index.js
- frontend/src/utils/changeFiles.js
- frontend/src/utils/deleteImage.js
- frontend/src/views/RegistProductView.vue
- 이미지 첨부 기능 구현
- 첨부 이미지 삭제 기능 구현
chanageFiles util 함수는 리팩토링 예정
> design: 상품 등록 UI 구현

- backend/Dockerfile
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
> Feat: Dockerfile 생성

- backend/README.md
> [backend] Test: jenkins test

- backend/README.md
> [backend] Test: scm ci

- frontend/package-lock.json
- frontend/package.json
> Fix: vue-fragment package 제거

- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/components/Button/SubmitButton.vue
- frontend/src/components/Form/CustomTextArea.vue
- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/components/ImageAttach.vue
- frontend/src/components/Title/ProductTitle.vue
- frontend/src/router/index.js
- frontend/src/utils/changeFiles.js
- frontend/src/utils/deleteImage.js
- frontend/src/views/ReportView.vue
- 신고 접수 UI를 구현
- CustomTextInput 수정
- CustomTextArea 구현
- ImageAttatch util 함수 수정
> Design: 신고 접수 UI 구현

- frontend/src/utils/changeFiles.js
- frontend/src/utils/changeImageToData.js
- frontend/src/utils/deleteImage.js
- frontend/src/utils/index.js
유틸 함수들 하나의 index.js 파일에 통합
utils 폴더에서 사용되는 함수들을 index.js 파일에 통합하였습니다.
index.js 파일만 다른 곳에서 import 하면 utils 폴더에 있는 함수들을 모두 사용할 수 있습니다
> Refactor: 유틸 함수들 하나의 index.js 파일에 통합

- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/views/ReturnRequestView.vue
> Design: 반품신청하기 페이지  UI 구현

- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/views/RegistProductView.vue
Refactor: customTextInput 컴포넌트 프롭스 추가
- customTextInput 컴포넌트 type과 가이드 텍스트 숨김여부 설정 props 추가
- 상품 등록 페이지 구입시기, 브랜드/모델명 추가
> Refactor: 상품 등록 페이지 변경된 util 함수 설정대로 수정

- frontend/src/views/ReportView.vue
- frontend/src/views/ReturnRequestView.vue
> Refactor: 변경된 util 함수 이름으로 import 수정

- frontend/src/views/HomeView.vue
- frontend/src/views/ProductsView.vue
> Feat: 전체 상품 리스트 UI 구현

- frontend/.eslintrc.js
- frontend/src/router/index.js
- 라우터 경로 추가
- 반품신청 
- 전체상품리스트 보기
- 결제하기
- 결제완료
- 프로필
- eslint 설정 변경
> Chore: 라우터 경로 추가

- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/components/Title/ProductTitle.vue
- frontend/src/router/index.js
- frontend/src/views/DeliveryRegistView.vue
- frontend/src/views/MypageView.vue
> Design: 배송등록 페이지 UI 구현

- frontend/src/components/Button/SubmitButton.vue
- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/views/EditProileView.vue
> Feat: 프로필 수정 화면 UI 작업 완료

- frontend/src/components/Button/MiniButton.vue
- frontend/src/components/CautionBlock.vue
- frontend/src/views/ProductDetailsView.vue
- frontend/src/views/PurchaseRequest.vue
- frontend/src/views/PurchaseRequestView.vue
상품 결제 페이지 UI를 구현했다.
https://github.com/EASYPEACH/shroop/assets/92674967/782cc2ef-541c-4a44-b0d6-a187db0337a4
> Feat: 상품 결제 페이지 UI 구현 완료

- frontend/src/components/Form/AgreementCheckBox.vue
- checkbox 컴포넌트 데이터 바인딩시 checked 옵션으로 바인드
> Fix: 체크박스 컴포넌트에 데이터 바인딩 잘못 된것 해결

- frontend/src/router/index.js
- frontend/src/views/ReportView.vue
- 신고 접수 게시물 제목 수정할 필요가 없어서 고정 텍스트로 수정
- 라우터 중복된 이름 수정
> Refactor: 신고접수 게시물 제목 일반 텍스트로 변경

- frontend/src/router/index.js
- 컴포넌트 임포트 방식 상단에서 하는 걸로 변경
- 로컬 환경에서 로드 속도 느린 이슈 해결
✅ 로컬 환경의 node 버전을 18로 변경해주세요
[vue-router lazy load](https://v3.router.vuejs.org/kr/guide/advanced/lazy-loading.html)
아래의 관련 내용은 더 찾아본 후 설명을 기재하겠습니다
[vite server options](https://ko.vitejs.dev/config/server-options.html)
> Fix: 컴포넌트 라우터 임포트 방식 변경

- frontend/src/components/CautionBlock.vue
- frontend/src/views/PurchaseRequestView.vue
체크박스 체크할때 전체해제되는 에러 해결
https://github.com/EASYPEACH/shroop/assets/72537762/049e121a-49bc-4ebf-a880-b6d0870be05b
watch 함수를 잘못사용해서 있었던 에러 입니다
> Fix: 체크박스 에러 해결

- frontend/Dockerfile
- frontend/docker/nginx.conf
- nginx에서 새로고침시 정적파일을 바라볼 수 있도록 세팅
> Chore: Docker nginx 설정 파일 추가

- frontend/src/views/EditProileView.vue
- 사용자 정보 입력 폼 유효성 검사 추가
- 버튼 사이즈 조정
> Refactor: 사용자 프로필 입력 폼 유효성 검사 추가

- backend/build.gradle
- backend/src/main/java/com/easypeach/shroop/infra/s3/S3Config.java
- backend/src/main/java/com/easypeach/shroop/infra/s3/service/S3UploadService.java
AWS S3를 Spring이랑 연동했다.
[S3 연동하기 참고 블로그](https://chb2005.tistory.com/200)
> Chore: S3를 연동한다

- backend/src/docs/asciidoc/auth.adoc
- backend/src/main/java/com/easypeach/shroop/modules/global/response/BasicResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/report/controller/ReportController.java
- backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
- backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
- backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImgRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportRepostiory.java
- backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportStatus.java
- backend/src/main/java/com/easypeach/shroop/modules/report/dto/ReportRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/report/dto/request/ReportRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
- backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
신고 및 중재하기 API를 구현했다.
해당 API의 테스트 코드도 작성했다.
product 기능 구현 후 필요한 부분 수정할 예정입니다.
> Feat: 신고 및 중재하기 API를 구현하다

- backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportImgService.java
> Refactor: 신고하기 API에 S3을 연동한다

- backend/README.md
> Test: cicd jenkins test

- backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
allowCredentials 설정 변경하여 쿠키 인증 가능하도록 수정
allowCredentials 과 쿠키 시간을 설정하였습니다
> Fix: allowCredentials 설정 변경하여 쿠키 인증 가능하도록 수정

- backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
- backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
스프링 시큐리티 설정 파일에서 CORS 설정을 하였습니다.
> Fix: 스프링 시큐리티에서 CORS 정책 설정 변경

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
> Refactor: 쿠키,세션에 맞는 로그인 정보로 리팩토링

- frontend/src/api/index.js
- frontend/src/api/modules/deleteApi.js
- frontend/src/api/modules/getApi.js
- frontend/src/api/modules/index.js
- frontend/src/api/modules/multipartPostApi.js
- frontend/src/api/modules/patchApi.js
- frontend/src/api/modules/postApi.js
axios API 요청에 사용할 컴포넌트 생성했다.
.env 파일 생성해야합니다.
내용은 슬랙으로 공유드리겠습니다.
> Feat: axios API 요청에 사용할 컴포넌트 생성

- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Grade.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductGrade.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductStatus.java
>  Feat: 상품 등급 및 상태 enum

- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
Product의 필드 값이 Grade -> ProductGrade로 수정
> Fix: Product의 Grade 필드명 수정

- frontend/src/api/index.js
- frontend/src/components/Button/SubmitButton.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/components/Modal/PlainModal.vue
- frontend/src/utils/index.js
- frontend/src/utils/multipartFormData.js
- frontend/src/views/ReportView.vue
> Feat: 신고하기 API을 프론트서버에 연동한다

- frontend/src/views/LoginView.vue
> Feat: 로그인 API 연동

- backend/build.gradle
- backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthClient.java
- backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
- backend/src/main/java/com/easypeach/shroop/infra/phone/dto/MessageRequest.java
- backend/src/main/java/com/easypeach/shroop/infra/phone/dto/PhoneAuthResponse.java
- backend/src/main/java/com/easypeach/shroop/infra/phone/dto/SmsRequest.java
> Feat: 문자발송 기능을 구현한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionCreateRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- Get 기능 추가 
- Validate 추가
- Final 추가
> Refactor: 상품 결제 API 리팩토링

- backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/controller/DuplicateValidController.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/DuplicateValidResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
> Feat: 아이디,닉네임,휴대전화 중복 검사 API 구현

- backend/.gitignore
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Grade.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductGrade.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductStatus.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/CategoryResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductCreatedResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/exception/CategoryNotFoundException.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/CategoryRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductImgRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- product controller
- 상품 등록 api 구현
> Feat: 상품 등록 API 구현

- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionCreateRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionInfoResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
> Feat: 결제 API 기능 추가(결제 시 상품 수정)

- frontend/.gitignore
- frontend/src/views/PurchaseCompleteView.vue
- frontend/src/views/PurchaseRequestView.vue
결제 API를 프론트 연동을 했다.
프론트에서 API 요청을 보내 받아온 값을 맵핑했다.
> Feat: 결제 API 프론트 연동

- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionInfoResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- frontend/src/views/PurchaseCompleteView.vue
- frontend/src/views/PurchaseRequestView.vue
- IMG를 Dto에 추가
- 그에 맞게 프론트 코드 변경
> Feat: 상품 결제 API 수정(IMG), 그에 맞게 프론트 연동

- backend/.gitignore
- backend/src/main/java/com/easypeach/shroop/infra/config/InitDb.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/CategoryRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/CategoryResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- 상품 수정 api
- 상품 카테고리 저장 api 수정
lombok의 Getter annotation을 사용하면 자동으로 boolean 값에 'is' 키워드가 생성됩니다.
그런데 이렇게 되면 objectmapper가 'get' 키워드가 아니어서, 해당 값을 boolean으로 직렬화하지 못하는 문제가 있었습니다.
따라서 request dto 필드값에 `@JsonProperty("isDefect")` 라는 
어노테이션을 주어서 해당 필드도 직렬화가 정상적으로 될 수 있도록 수정했습니다
[lombok 사용시 boolean 직렬화 하기](https://web2eye.tistory.com/245)
> Feat: 상품 수정 API를 구현한다

- backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
> Refactor: 신고하기 API 테스트 코드를 리팩토링한다

- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/SellerPurchaseException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- productId로 product 찾아오는 코드를 컨트롤러에서 서비스로 옮겼다.
- Exception 클래스를 만들고, product에 담겨있는 Seller의 id와 로그인해서 구매하는 구매자의 id가 같을 시 에러가 발생하게 만들었다.
> Refactor: 예외 처리 및 컨트롤러 리팩토링

- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/components/Form/PhoneInput.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/router/index.js
- frontend/src/store/signUp.js
- frontend/src/views/PhoneAuthView.vue
- frontend/src/views/SignupView.vue
- 회원 가입 API 연동
- 휴대전화 본인 인증 API 연동
- 포커스 아웃 시, 아이디,닉네임,휴대전화 중복 검사
> Feat: 프론트 회원 가입 API 연동

- frontend/package.json
쿠키 라이브러리 package.json 파일에 추가
쿠키 라이브러리 package.json 파일에 추가하지 않아서 젠킨스 빌드에서 에러가 발생하였음
> Chore: 쿠키 라이브러리 의존성 추가

- backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/LoginCheckResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
로그인 여부를 알려주는 API 구현
- 로그인 성공 시
{
"memberId": 1,
"loginId": "abc123123",
"nickname": "abc123123",
"result": true
}
- 로그인 실패 시
{
"memberId": -1,
"loginId": "",
"nickname": "",
"result": false
}
> Feat: 로그인 여부를 알려주는 API 구현

- frontend/src/api/modules/index.js
- frontend/src/components/Button/NotifyBellButton.vue
- frontend/src/components/NotifyBar.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/store/useCheckLogin.js
- frontend/src/store/useNotifyList.js
프론트에 알림 API를 연동한다.
알림부분을 컴포넌트로 수정했다.
pinia를 이용해서 알림 데이터를 전역 변수로 사용했다.
> Feat: 프론트에 알림  API를 연동한다

- backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/LoginCheckResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
- backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
AuthController 에서 MemberService 를 사용하였는데,
AuthControllerTest 에서  MemberService  가 목빈으로 존재하지 않아 테스트가 실행되지 않는 이슈 발생
MemberService  목으로 주입
> Fix: AuthControllerTest 에서 테스트가 실패하는 이슈 수정 

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/BuyerResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/TransactionNotExistException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
> Feat: 구매자 정보 조회 API를 구현한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
- 결제 API 테스트 코드 작성
- 컨트롤러 -> 서비스로 메소드 위임
> Feat: 상품 결제 API 테스트 코드 작성 및 리팩토링을 한다.

- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/MemberResonse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductImgResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/exception/ProductException.java
- backend/src/main/java/com/easypeach/shroop/modules/product/exception/ProductImgLengthException.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductImgRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
> Feat: 상품 조회 api 구현

- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductReturnController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturn.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturnImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductReturnRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnImgRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductReturnControllerTest.java
반품하기 API를 구현했다.
테스트 코드 작성도 완료했다.
> Feat: 반품하기 API를 구현한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
구매 취소하기 API를 구현했다.
테스트 코드도 구현했다.
> Feat: 구매 취소하기 API를 구현한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/IsNotBuyerException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
구매 확정하기 API를 구현했다
구매 확정시, 판매자에게 포인트가 추가되도록 했다.
> Feat: 구매 확정하기 API를 구현한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/IsNotSellerException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
반품 확정하기 API를 구현했다.
반품 확정시, 구매자에게 포인트가 추가되도록 구현했다.
> Feat: 반품 확정하기 API를 구현한다

- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- product response service에 판매자 set을 추가했다
> Refactor: product response service에 판매자 set 추가

- frontend/src/App.vue
- frontend/src/views/SignupView.vue
> Fix: 인증번호 확인 화면 라우터 체크에서 제외

- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
- frontend/src/components/Banner/MypageProductBanner.vue
- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/consts/status.js
- frontend/src/views/MypageView.vue
- frontend/src/views/PurchaseRequestView.vue
- 구매내역 API를 호출했다.
- 판매내역 API를 호출했다.
프론트 bug 사항 때문에 일단 merge를하고 프론트 paging처리는 추후에 merge하는 걸로!
> Feat: 판매내역 & 구매내역 API를 마이페이지에서 호출했다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryControllerTest.java
- frontend/src/components/Banner/MypageProductBanner.vue
- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/consts/status.js
- frontend/src/views/MypageView.vue
- frontend/src/views/PurchaseRequestView.vue
> Feat: 내역 조회 API의 DTO를 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/notification/domain/NotificationRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
생성일자 내림차순으로 알림 리스트를 반환하도록 수정했다
> Refactor: 생성일자 내림차순으로 알림 리스트를 반환하도록 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
> Refactor: 반품 신청시 알림가도록 수정했다

- frontend/src/components/Banner/MypageProductBanner.vue
> Feat: 프론트에 반품 확정하기 API를 연동한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/DeliveryController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Delivery.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/DeliveryRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/DeliveryRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/DeliveryService.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/DeliveryControllerTest.java
> Feat: 택배 등록하기 API를 구현한다

- frontend/src/views/ProductDetailsView.vue
- 배송비 관련 데이터 프로퍼티 수정: 배송비 정보 정확하게 노출
- 모달 취소 핸들러 구현
> Fix: 모달 취소 핸들러 추가 구현

- backend/src/main/java/com/easypeach/shroop/modules/like/controller/LikeController.java
- backend/src/main/java/com/easypeach/shroop/modules/like/domain/LikeRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/like/service/LikeService.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/controller/LikeController.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/domain/LikeRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/exception/LikesProductNotFoundException.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/service/LikeService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- backend/src/test/java/com/easypeach/shroop/modules/likes/controller/LikeControllerTest.java
- 좋아요 API 구현
- 좋아요 API test 구현
> Feat: 좋아요 API 구현

- frontend/src/views/DeliveryRegistView.vue
> Feat: 배송등록 API 연동

- frontend/src/views/EditProileView.vue
> Feat: 프로필 수정 API 연동

- frontend/.env.production
> Remove: env.production 제거

- frontend/src/views/HomeView.vue
- frontend/src/views/ProductsView.vue
- 좋아요 API 호출해주는 util 함수 앞에 await 추가
-
> Fix: 상품 카드 좋아요 클릭시 예외처리 안해주는 버그 수정

- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/components/Button/LikeButton.vue
- frontend/src/components/Form/CustomTextArea.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/ProductDetailsView.vue
- frontend/src/views/PurchaseCompleteView.vue
- frontend/src/views/RegistProductView.vue
구매하기 화면에서 거래완료 뱃지를 제거한다
로그인 이후 이동경로를 이전페이지로 수정한다
> Fix: 구매하기 화면에서 거래완료 뱃지를 제거한다

- backend/src/main/java/com/easypeach/shroop/modules/bank/domain/Bank.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/domain/BankRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- Bank Entity 생성
- Member에 계좌 필드, 세터 세팅
원래 클라이언트에서 포인트 충전, 환전 요청을 Shroop으로 보내면 저희가 은행으로 결제 요청을 보내야하는데, 저희가 은행을 갖고 있고 때문에, 저희에게 요청을 보낼 수 없어 컨트롤러는 만들지 않았습니다! 개념적으로 갖고 있긴 하지만 최대한 세분화 하기 위해서 금액을 바꾸기 위해 서비스와 레포지토리 까지는 만들어뒀습니다!
> Chore: Bank Entity 생성

- frontend/src/App.vue
- frontend/src/api/index.js
- frontend/src/components/ApiLoader.vue
- frontend/src/layouts/default/DefaultLayout.vue
- frontend/src/router/index.js
- frontend/src/store/useLoading.js
- api 요청 => IsLoading 전역상태 true
- api 요청성공 => isLoading 전역상태 false
- api 요청/응답 실패 => isLoading 전역상태 false , 상태코드에 따라 예외처리
> Feat: 로딩 UI 구현

- backend/build.gradle
- backend/src/main/java/com/easypeach/shroop/infra/config/QuerydslConfig.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/SearchRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductOneImgResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/SearchProductResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustom.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
상품 검색하기 API를 구현했다
queryDsl를 이용해서 동적쿼리를 구현했다
> Feat: 상품 검색하기 API를 구현한다

- frontend/src/components/Button/LikeButton.vue
- frontend/src/components/Button/NotifyBellButton.vue
- frontend/src/components/Card/ProductCard.vue
- frontend/src/components/Form/PasswordInput.vue
- frontend/src/components/NotifyBar.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/router/index.js
- frontend/src/views/DeliveryRegistView.vue
- frontend/src/views/EditProileView.vue
- frontend/src/views/HomeView.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/PhoneAuthView.vue
- frontend/src/views/ProductDetailsView.vue
- frontend/src/views/PurchaseCompleteView.vue
- frontend/src/views/PurchaseRequestView.vue
- frontend/src/views/RegistProductView.vue
- frontend/src/views/ReportView.vue
- frontend/src/views/ReturnRequestView.vue
- frontend/src/views/SignupView.vue
- 사용하지 않는 콘솔 제거
- axios 에러 console.errror로 처리
- 사용하지 않는 변수 제거
- import 순서 정리
> Fix: 전체 코드 리팩토링 및 정리

- backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/LikeProductInfo.java
마이페이지에 추가로 필요한 데이터 dto 추가
- 카테고리, 생성날짜
- 프론트에 사용된 변수명에 맞게 변수명 변경
현재 카테고리 엔티티가 DTO에 노출되고 있음
프론트에 맞게 보여주기 위해 시간상 현재 코드로 적용하고 추후에 DTO로 수정 필요
> Refactor: 마이페이지에 추가로 필요한 데이터 dto 추가

- frontend/src/views/MypageView.vue
마이페이지 API 연동
- 회원 정보 API
- 좋아요 목록 페이징
> Feat: 마이페이지 API 연동

- frontend/src/components/Button/NotifyBellButton.vue
> Refactor: 알림 아이콘을 변경한다

- frontend/src/App.vue
- frontend/src/components/Button/HamburgerButton.vue
- frontend/src/components/Navigation/SideNavigation.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/layouts/default/DefaultLayout.vue
- frontend/src/plugins/vuetify.js
- frontend/src/store/useMobileNav.js
- frontend/src/store/useNotifyList.js
- frontend/src/views/HomeView.vue
- frontend/src/views/PurchaseRequestView.vue
Feat: 모바일 햄버거 버튼 구현 .모바일용 사이드바 구현
> Feat: 검색 UI 추가 구현

- backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
> Bug: 상태값 변경에 따라 로직 수정

- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/BuyerResponse.java
- frontend/src/components/Banner/MypageProductBanner.vue
> Feat: 프론트에 구매자정보 조회 API를 연동한다

- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
반환값에 대한 변수명 수정에 따라 테스트 코드 수정했다
> Bug: 반환값에 대한 변수명 수정에 따라 테스트 코드 수정

- frontend/src/utils/changeUrlToFiles.js
- frontend/src/views/EditProileView.vue
- fetch에 no-cache 설정을 추가하여 오류를 해결했습니다
> Fix: s3 cors 오류 해결

- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
구매 확정시 , 슈룹계정에서 보관하고 있던 포인트를 판매자에게 추가한다.
반품 확정시, 슈룹계정에서 보관하고 있던 포인트를 구매자에게 추가한다.
> Refactor: 결제 로직 수정으로 인해 구매확정, 반품확정 로직을 수정했다.

- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductOneImgResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
- frontend/src/components/Button/LikeButton.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/main.js
- frontend/src/plugins/index.js
- frontend/src/utils/toggleLikesProduct.js
- frontend/src/views/HomeView.vue
- frontend/src/views/ProductsView.vue
- 상단 헤더 로고 클릭 영역 수정
- 홈화면 API 연결 수정
- 검색시 앞뒤 공백 제거
- 홈화면으로 돌아갔을때 검색창 초기화
- 검색 API 데이터 정렬
> Refactor: 홈화면 리팩토링

- backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
> Refactor: 신고 이미지 엔티티에 cascade 설정을 추가했다

- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
> Refactor: 카테고리명에 유니크 설정을 추가했다

- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
상품 검색하기 API의 반환값이 변경되어 그에 맞게 테스트 코드를 수정했다.
like -> isLike로 수정했다.
> Bug: 상품 검색하기 API의 테스트 코드를 수정했다

- backend/src/docs/asciidoc/report.adoc
- backend/src/main/resources/static/report.html
- backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
Rest Docs에 맞게 신고하기 테스트 코드를 수정했다.
> Test: 신고하기 API 테스트 코드를 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberInfo.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
회원 탈퇴 처리 로직 구현
회원 상태에 ROLE_DELETE 를 추가하였습니다
ROLE_DELETE 인 유저는 정해진 기간이 지나면 삭제하도록 구현 필요
> Feat: 회원 탈퇴 처리 API 구현

- backend/src/docs/asciidoc/notification.adoc
- backend/src/main/resources/static/notification.html
- backend/src/test/java/com/easypeach/shroop/modules/notification/controller/NotificationControllerTest.java
> Test: 알림 API 테스트 코드를 수정했다

- backend/src/docs/asciidoc/delivery.adoc
- backend/src/main/resources/static/delivery.html
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/DeliveryControllerTest.java
> Test: 배송 API의 테스트 코드를 수정했다

- frontend/src/router/index.js
- frontend/src/views/NotFound.vue
찾을 수 없는 경로로 진입했을 때 나오는 404페이지를 추가했다.
> Feat: 404페이지를 추가했다

- backend/src/docs/asciidoc/auth.adoc
- backend/src/docs/asciidoc/member.adoc
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberSignInRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberSignUpRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
- backend/src/main/resources/static/auth.html
- backend/src/main/resources/static/index.html
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
> Feat: 회원,인증 관련 테스트 코드 작성

- frontend/src/views/EditProileView.vue
- frontend/src/views/MypageView.vue
탈퇴 API 프론트 연동
- 프로필 수정 페이지 마이페이지로 이동
- 탈퇴 기능 추가
> Feat: 탈퇴 API 프론트 연동

- backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
이미지 파일이 넘어오지 않을 경우 List 는 null 인 상태에서
list.size()를 체크하려고 하여 null 에러 발생
> Fix: 이미지 파일이 넘어오지 않을 경우 null 이슈 처리

- backend/src/docs/asciidoc/return.adoc
- backend/src/docs/asciidoc/transaction.adoc
- backend/src/main/resources/static/return.html
- backend/src/main/resources/static/transaction.html
- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductReturnControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
거래 관련 API 테스트 코드를 수정했다.
- 구매자조회
- 구매취소
- 구매확정
- 반품요청
- 반품확정
> Test: 거래 관련 API 테스트 코드를 수정했다

- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
> Fix: 상품 응답 DTO 내부에 카테고리 타입 변경

- frontend/src/views/auth/index.js
- frontend/src/views/mypage/index.js
- frontend/src/views/product/index.js
- frontend/src/views/transaction/index.js
> Fix: 라우터 뷰 경로 수정

- backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
- backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
신고 신청할 경우 신고 받은 사람 정보도 추가하도록 수정했다
> Refactor: 신고 신청할 경우 신고 받은 사람 정보도 추가하도록 수정했다

- backend/src/main/java/com/easypeach/shroop/infra/s3/service/S3UploadService.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportImgService.java
- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
현재 상품 등록 시 로직
1. 상품을 등록 
2.  상품이미지에 상품을 연결
3.  상품이미지 저장
변경된 상품 등록 로직
1. 상품에 상품 이미지 연결
2. 상품 저장
> Feat: 상품 등록 로직 수정

- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/DeliveryService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- 알림 관련 api에서 리턴해주는 마이페이지 경로를 프론트의 경로에 맞게 수정해주었다.
-
> Fix: 마이페이지 라우터 경로 수정

- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
> Fix: 예외처리 코드 수정 안된부분을 다시 적용

- frontend/src/App.vue
- frontend/src/views/auth/LoginView.vue
> Feat: 차단,탈퇴한 계정 실패 사유 로그인창에 노출

- frontend/src/components/Form/PasswordInput.vue
- frontend/src/components/Form/PhoneInput.vue
- input에 value가 잘못 바인딩 되어있는 부분을 수정했다
> Refactor: value-bind 잘못된 것 수정

- frontend/src/views/mypage/MyPagePurchaseListView.vue
- frontend/src/views/mypage/MyPageSellListView.vue
- frontend/src/views/mypage/MypageEditProfileView.vue
- frontend/src/views/mypage/MypageHomeView.vue
> Fix: 마이페이지 판매내역 페이지네이션 액티브 안되는 오류 수정

- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
상품 조회시 사용자의 이미지URL, 등급 점수를 가져올 수 있도록 DTO 수정
> Feat: 사용자의 이미지URL, 등급 점수를 가져올 수 있도록 DTO 수정한다

- frontend/src/App.vue
> Fix: 로그인 안되었을때 계속 새로고침 되는 오류를 수정

- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
> Fix: 상품 조회 테스트 코드를 수정한다

- frontend/src/views/mypage/MypageHomeView.vue
> Feat: 마이페이지 점수별 등급이 노출되도록 수정한다

- frontend/src/components/Modal/ImageThumbModal.vue
- frontend/src/components/Modal/index.js
- frontend/src/views/product/ProductDetailsView.vue
- 상품 상세페이지 결함 이미지 크기 조정
- 이미지 썸네일 팝업 추가
> Fix: 상품 상세 페이지 결함 이미지 크기 조정

- backend/src/docs/asciidoc/member.adoc
- backend/src/docs/asciidoc/transaction.adoc
- backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
- backend/src/main/java/com/easypeach/shroop/modules/member/controller/PointController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/PointResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/PointRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/main/resources/static/auth.html
- backend/src/main/resources/static/category.html
- backend/src/main/resources/static/delivery.html
- backend/src/main/resources/static/index.html
- backend/src/main/resources/static/likes.html
- backend/src/main/resources/static/member.html
- backend/src/main/resources/static/notification.html
- backend/src/main/resources/static/product.html
- backend/src/main/resources/static/report.html
- backend/src/main/resources/static/return.html
- backend/src/main/resources/static/transaction.html
- backend/src/test/java/com/easypeach/shroop/modules/bank/controller/BankControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/member/controller/PointControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryControllerTest.java
- frontend/src/components/Modal/ChargePointModal.vue
- 거래 API 문서화
- 거래 내역 리팩토링 및 문서화
- 포인트 API 문서화
LONG 타입을 입력받고 반환하던 포인트 API를 문서화하는데 RestDocs가 객체로 문서화를 해줘서 Long타입을 넣을 방법이 없어 DTO로 리팩토링 했습니다!
> Test: 거래, 거래 내역, 포인트 Test 코드를 리팩토링하고 문서화 했다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- frontend/src/views/transaction/PurchaseCompleteView.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
> Refactor: 거래 리팩토링을 한다

- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- 수정된 프로필 이미지 검사시 null을 검사하도록 로직 변경
- 휴대전화 인증 체크 후 휴대전화번호 변경하도록 수정
> Fix: 프로필 수정 로직을 수정한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
구매 확정되면 판매자의 회원등급이 상승되도록 수정했다.
> Refactor: 구매 확정되면 판매자의 회원등급이 상승되도록 수정했다

- frontend/public/manifest.json
- frontend/vite.config.js
- package-lock.json
> Fix: 코드 오타를 수정한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/DeliveryController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/DeliveryRequest.java
- frontend/src/components/Form/data/formRules.js
- frontend/src/views/transaction/DeliveryRegistView.vue
> Refactor: 운송장번호는 숫자만 입력가능하도록 수정했다

- frontend/src/components/Form/PhoneInput.vue
- frontend/src/views/auth/SignupView.vue
회원가입 시 유효성을 통과하지 않아도 다음 버튼이 활성화되는 이슈를 수정하였습니다
> Fix: 회원가입 유효성, 중복 체크가 완료되어야 다음 버튼이 활성화되도록 수정

- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
로그인되어 있지않으면 좋아요는 무조건 false로 나오도록 수정했다
> Bug: 상품 검색 조회 시 좋아요가 잘못나오는 부분 수정했다

- frontend/src/views/product/ProductsView.vue
상품 전체 조회 API를 호출하는 부분에서 이동할 페이지로 조건 처리하도록 수정했다.
> Refactor: 상품 전체 조회 요청하는 부분을 수정했다.

- frontend/src/App.vue
- frontend/src/components/Banner/MypageProductBanner.vue
- frontend/src/views/mypage/MyPagePurchaseListView.vue
- frontend/src/views/mypage/MyPageSellListView.vue
- frontend/src/views/mypage/MypageEditProfileView.vue
Fix: 마이페이지 삭제하기 API 연동
Fix: 프로필 조회시 로더 UI 제거
> Fix: 마이페이지 삭제하기 API 연동

- frontend/src/views/auth/LoginView.vue
> Refactor: 로그인 실패시 패스워드 초기화를 하도록 한다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
> Refactor: 구매취소 시 구매자에게 포인트 환불되도록 수정했다

- frontend/src/views/HomeView.vue
모바일 환경에서는 밑에서 위로 올라오도록 모션을 수정했다
> Fix: 모바일 환경에서의 모션 수정

- frontend/src/components/Button/HamburgerButton.vue
- frontend/src/components/ProductCard.vue
- frontend/src/components/Title/ProductTitle.vue
- frontend/src/layouts/ContentLayout.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/layouts/default/DefaultFooter.vue
- frontend/src/layouts/default/DefaultLayout.vue
- frontend/src/layouts/default/MobileAppBar.vue
- frontend/src/views/product/ProductDetailsView.vue
- frontend/src/views/report/ReportView.vue
- 상품 상세페이지 모바일에서 틀어짐 수정
- 모바일 페이지별로 상단 바 UI 변경
> Refactor: 모바일 환경에서의 UI 틀어짐 수정

- backend/src/main/java/com/easypeach/shroop/modules/bank/dto/LinkBankRequest.java
- frontend/src/components/Modal/LinkAccountModal.vue
- dto 유효성 검사 수정
- 프론트 엔드 유효성 검사 추가
> Refactor: 계좌 연동 리팩토링을 했다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionCreateRequest.java
- frontend/src/components/Modal/LinkAccountModal.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
- 계좌 연동 시 새로고침하게 수정
- 결제 창 상세주소 유효성 검사 수정
- 결제 창 모두 체크 버튼 수정
> Refactor: 계좌연동 및 결제창 리팩토링

- backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/domain/PhoneAuth.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/PhoneAuthUUID.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/exception/AuthFailCountException.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/exception/AuthTimeOutException.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthCountService.java
- backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
- frontend/package-lock.json
- frontend/src/views/auth/PhoneAuthView.vue
- frontend/src/views/auth/SignupView.vue
휴대전화인증 리팩토링
- 인증번호 재요청 기능 추가
- 인증 제한 시간 추가
- 인증 5회 실패 시 회원가입 페이지로 이동
> Feat: 휴대전화인증 리팩토링

- frontend/src/components/Form/data/formRules.js
- frontend/src/components/Modal/ChargePointModal.vue
- frontend/src/components/Modal/LinkAccountModal.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
- Rules 추가
- 포인트 충전 유효성 검사 추가
- 계좌번호 유효성 검사 추가
> Refactor: 유효성 검사 추가를 했다

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Banner/MypageProductBanner.vue
- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/components/Button/LikeButton.vue
- frontend/src/components/ImageAttach.vue
- frontend/src/components/ProductCard.vue
- frontend/src/components/ProductSwiper.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/layouts/default/DefaultLayout.vue
- frontend/src/layouts/default/MobileAppBar.vue
- frontend/src/plugins/vuetify.js
- frontend/src/styles/global.style.css
- frontend/src/views/HomeView.vue
- frontend/src/views/mypage/MypageEditProfileView.vue
- frontend/src/views/mypage/MypageHomeView.vue
- frontend/src/views/mypage/MypageView.vue
- frontend/src/views/product/ProductDetailsView.vue
- frontend/src/views/product/ProductsView.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
- package-lock.json
- 홈화면 UI 수정
- 마이페이지 UI 수정
- 상품 상세페이지 UI 수정
> Style: UX의  개선

- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
> Fix: 본인 인증 테스트 코드 수정

- frontend/src/views/auth/PhoneAuthView.vue
> Fix: 인증 제한 시간 0으로 나오는 현상 수정

- frontend/package-lock.json
- frontend/src/components/Form/AgreementDialog.vue
- frontend/src/components/Form/data/usageRules.js
> Feat: 회원가입 동의 약관 샘플 추가

- frontend/src/components/Banner/MypageProductBanner.vue
구매확정, 반품확정, 구매취소 모달 확인 클릭 시 모달이 사라지도록 수정했다.
> Fix: 구매확정, 구매취소, 반품확정 확인 클릭 시 모달이 사라지도록 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
- backend/src/main/resources/import.sql
상품 전체 조회 시 좋아요 개수만큰 중복 조회되는 오류를 수정했다.
> Fix: 상품 전체 조회 시 좋아요 개수만큰 중복 조회되는 오류를 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
좋아요 기능 동시성을 리팩토링했다.
- 테이블에 유니크 제약조건 추가
- 낙관적락 적용
> Refactor: 좋아요 기능 동시성을 리팩토링했다

- frontend/src/components/Modal/ImageThumbModal.vue
- frontend/src/components/ProductSwiper.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/views/mypage/MyPagePurchaseListView.vue
- frontend/src/views/mypage/MyPageSellListView.vue
- frontend/src/views/mypage/MypageEditProfileView.vue
- frontend/src/views/mypage/MypageHomeView.vue
- frontend/src/views/product/ProductDetailsView.vue
마이페이지 콘텐츠의 상단 여백을 제거해서 어색함을 없앴습니다
> Design: 마이페이지 컨텐츠 상단 여백 제거

- backend/src/main/java/com/easypeach/shroop/infra/aop/likes/Retry.java
- backend/src/main/java/com/easypeach/shroop/infra/aop/likes/RetryAspect.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/service/LikeService.java
좋아요 기능 동시성 이슈를 수정했다.
낙관적 락 이후, 재시도 되도록 수정했다.
> Refactor: 좋아요 기능 동시성 이슈를 수정했다

- frontend/src/components/Modal/ChargePointModal.vue
- frontend/src/components/Modal/LinkAccountModal.vue
- frontend/src/views/HomeView.vue
> Design: 계좌연동 UI 변경

- backend/src/docs/asciidoc/index.html
- backend/src/main/resources/static/auth.html
- backend/src/main/resources/static/category.html
- backend/src/main/resources/static/delivery.html
- backend/src/main/resources/static/index.html
- backend/src/main/resources/static/likes.html
- backend/src/main/resources/static/member.html
- backend/src/main/resources/static/notification.html
- backend/src/main/resources/static/product.html
- backend/src/main/resources/static/report.html
- backend/src/main/resources/static/return.html
- backend/src/main/resources/static/transaction.html
> Fix: restdocs 경로 수정

- frontend/cypress/e2e/transactionTest.cy.js
- frontend/src/components/Modal/ChargePointModal.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
> Test: 결제하기 단위 테스트

- frontend/src/components/Modal/ImageThumbModal.vue
- frontend/src/components/ProductSwiper.vue
- frontend/src/layouts/MypageLayout.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/views/mypage/MyPagePurchaseListView.vue
- frontend/src/views/mypage/MyPageSellListView.vue
- frontend/src/views/mypage/MypageHomeView.vue
- frontend/src/views/mypage/MypageView.vue
- frontend/src/views/product/ProductDetailsView.vue
> Refactor: 마이페이지 레이아웃 및 여백 수정

- backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
- backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
> Refactor: 인증 문자 메세지 내용을 수정했다

- frontend/src/views/mypage/MypageEditProfileView.vue
> Refactor: 회원 수정페이지에서 비밀번호 숨기기 기능 수정했다

- frontend/src/components/ProductSwiper.vue
> Fix: 스와이퍼 높이 수정

- backend/src/test/java/com/easypeach/shroop/concurrency/ProductConcurrencyTest.java
좋아요를 2명이 동시에 클릭한 경우 예외가 발생하여도 Retry 애노테이션에 의해
2명 모두 좋아요 클릭이 되어야 한다
https://codechacha.com/ko/java-countdownlatch/
> Test: 좋아요 동시성 테스트 코드를 작성한다

- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
> Refactor: 차단/탈퇴된 유저의 게시물은 안보이도록 수정했다

- backend/src/test/java/com/easypeach/shroop/modules/member/controller/PointControllerTest.java
> Refactor: 포인트 테스트 리팩토링을 한다

- frontend/src/components/Modal/LinkAccountModal.vue
- frontend/src/views/mypage/MypageHomeView.vue
- 마이프로필 포인트에 toLocaleString
- 계좌번호에 placeholder
> Refactor: 포인트 및 계좌 리팩토링

- backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/MyPageInfoResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
> Refactor: 마이페이지에서 회원 정보 DTO 를 수정한다

- backend/src/main/java/com/easypeach/shroop/infra/aop/likes/RetryAspect.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/resources/import.sql
- backend/src/test/java/com/easypeach/shroop/concurrency/ProductConcurrencyTest.java
> Feat: 좋아요 더미 데이터 삭제

- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductReturnController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturn.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturnImg.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductReturnImgResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductReturnResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnImgRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
> Feat: 반품 조회 API를 구현했다

- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
> Refactor: dto 수정

- frontend/package-lock.json
- frontend/src/views/mypage/MypageEditProfileView.vue
휴대전화인증 제한 시간 추가
- 휴대전화번호 변경 없으면 인증하기 버튼 잠금 처리
> Refactor: 휴대전화인증 제한 시간 추가

- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/DuplicateTrackingNumberException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/DeliveryService.java
> Refactor: 배송 등록 시 운송장번호 중복 검사하도록 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/ProfileEditForm.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
개인정보수정 화면에서 로그인 아이디가 보이도록 DTO 수정
> Refactor: 개인정보수정 화면에서 로그인 아이디가 보이도록 DTO 수정

- frontend/src/components/Form/CustomTextArea.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/views/auth/LoginView.vue
- frontend/src/views/product/RegistProductView.vue
- frontend/src/views/report/ReportView.vue
- frontend/src/views/transaction/DeliveryRegistView.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
> Refactor: 글자수 제한 기능을 추가했다

- frontend/src/router/index.js
- frontend/src/views/transaction/ReturnRequestResultView.vue
- frontend/src/views/transaction/index.js
> Refactor: 반품 관련 상세페이지를 추가하고 반품 처리를 한다

- frontend/src/components/Banner/MypageProductBanner.vue
- frontend/src/views/mypage/MypageEditProfileView.vue
- frontend/src/views/transaction/PurchaseCompleteView.vue
> Refactor: 구매취소가 되지 않는 오류를 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/ImageAttach.vue
- frontend/src/utils/changeUrlToFiles.js
- frontend/src/utils/compressImage.js
- frontend/src/utils/index.js
- frontend/src/views/mypage/MypageEditProfileView.vue
- frontend/src/views/product/RegistProductView.vue
- frontend/src/views/report/ReportView.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
- frontend/src/views/transaction/ReturnRequestView.vue
- 프론트에서 이미지를 첨부할때 이미지 용량을 최적화 했다
- 프론트에서 이미지 첨부시 이미지 이름이 한글이 있을 경우 => 상품 삭제를 하면 => S3에서 삭제가 안되었음 => 저장시 이름을 영문 + 숫자로 램덤값을 주어 해결
- 상품 삭제 혹은 프로필 이미지 수정시 이전 이미지를 저장소에서 삭제한다
pull 받고 npm install 부탁드리겠습니다!
> Refactor: 이미지 최적화를 진행했다

- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Form/CustomTextArea.vue
- frontend/src/components/ImageAttach.vue
- frontend/src/utils/changeUrlToFiles.js
- frontend/src/utils/compressImage.js
- frontend/src/utils/index.js
- frontend/src/views/mypage/MypageEditProfileView.vue
- frontend/src/views/product/RegistProductView.vue
- frontend/src/views/report/ReportView.vue
- frontend/src/views/transaction/PurchaseRequestView.vue
- frontend/src/views/transaction/ReturnRequestView.vue
> Fix: textarea 설정을 변경했다
