- frontend/src/components/Form/CustomTextInput.vue
- frontend/src/components/Form/PasswordInput.vue
- frontend/src/components/Form/data/formRules.js
- frontend/src/components/Title.vue
- frontend/src/plugins/vuetify.js
- frontend/src/views/Login.vue
- Title 컴포넌트 구현
- CustomTextInput 컴포넌트 구현
- PasswordInput 컴포넌트 구현
- label: input의 제목으로 쓰일 텍스트
- placeholderText: input 내부 가이드 텍스트
- modelValue: v-model로 input과 연동할 data
- rules: 기본 패턴, 규칙, 필수여부 등 
- modelValue: v-model로 input과 연동할 data
- visible: input type 변경하는 boolean 값
- isNeedSearchState: 비밀번호 찾기 버튼 노출 여부
> Design: 로그인 페이지 UI 구현

- backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
> fix: CORS를 설정한 WebConfig를 빈으로 등록

- frontend/src/views/ProductDetailsView.vue
> Fix: 구매하기 버튼 영역 확장

- frontend/src/layouts/default/AppBar.vue
- frontend/src/router/index.js
- frontend/src/views/MypageView.vue
- frontend/src/views/PurchaseCompleteView.vue
구매내역 상세 페이지  UI 구현
https://github.com/EASYPEACH/shroop/assets/72537762/e3e4ad26-98ca-4c78-a055-7a7fabd35d46
- 구매자가 구매완료 후 마이페이지의 구매내역 탭으로 이동
- 판매자가 운송장 등록후 마이페이지의 판매내역 탭으로 이동
위 두가지를 위해 마이페이지 탭에 라우트 규칙을 추가했습니다
> Design: 구매내역 상세 페이지  UI 구현

- backend/src/main/java/com/easypeach/shroop/ShroopApplication.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Delivery.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionStatus.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionInfoResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- 결제 페이지 조회
- 결제 API 구현
- GET 요청 시 상품의 제목, 가격, 고객의 포인트를 Resoponse로 제공합니다.
- POST 요청 시 거래를 DB에 저장하고, 고객의 포인트를 차감한 뒤, 결제 완료 페이지에 보여줄 데이터들을 제공합니다.
> Feat: 결제 기능 구현

- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
공통으로 상속 받고 있는 ControllerTest에서 MemberService을 MockBean으로 추가했기 때문에 제거한다.
> Fix: 구매자정보 조회 API 테스트 코드 오류를 수정한다

- backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductReturnControllerTest.java
유효성 검사에서 내용이 30자 이상이기 때문에 30자 이상으로 수정했다.
> Fix: 반품하기 API 테스트 코드 수정을 수정한다

- backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
logout 호출 시 세션에서 사용자 로그인 정보 제거
logout 호출 시 세션에서 사용자 로그인 정보 제거
logout 호출 시 사용자 정보가 세션에서 제거된 것은 확인했으나
deleteCookies 를 설정해줘도 클라이언트에서 쿠키는 남아있음
https://stackoverflow.com/questions/43773840/spring-security-delete-cookie-for-logout
> Feat: logout 호출 시 세션에서 사용자 로그인 정보 제거

- backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/member/controller/PointController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/domain/ShroopMember.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/LackOfPointException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/SellerPurchaseException.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/main/resources/import.sql
- backend/src/test/java/com/easypeach/shroop/modules/member/controller/PointControllerTest.java
결제 시 고객에게 차감한 포인트를 보관하는 기능과 수수료를 슈룹 계좌에 넣는 로직 추가
결제 시 고객의 포인트에서 상품 가격과 수수료를 더한 금액을 차감했습니다. 이에 따라상품의 가격만큼 슈룹 보관소에 포인트를 보관했고, 수수료는 슈룹의 계좌로 넣어줬습니다.
> Refactor: 포인트 도입에 따른 거래 로직 수정

- backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/controller/BankController.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/domain/Bank.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/dto/LinkBankRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/exception/AccountMismatchException.java
- backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
- backend/src/main/resources/import.sql
- 계좌 연동하기 API 리팩토링
- 계좌 생성 API 구현
- 계좌 연동 창에서 4자리의 비밀번호가 입력되면, 암호화하여 은행의 암호화된 번호와 일치하는지 확인하고 ,이름도 일치하는지 확인하고 일치하면 멤버의 계좌와 연동시켜주는 로직입니다.
- 계좌를 생성하는 창은 필요하지 않고, sql 파일에 더미 데이터를 넣기 번거로울거 같아서 포스트맨 용으로 계좌 생성 API를 만들어 뒀습니다.
@jiny798 가 알려준 PasswordEncoder
> Refactor: 계좌 연동하기 API 리팩토링, 계좌 생성 API 구현

- backend/build.gradle
- backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserLog.java
- backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserLogDto.java
- backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserLogRepository.java
- backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserTrace.java
- backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserTraceAspect.java
- backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationSuccessHandler.java
- backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/controller/LikeController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
- backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
- backend/src/main/java/com/easypeach/shroop/modules/report/controller/ReportController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/DeliveryController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
AOP 로그 추적기 구현
- 로그인, 상품 등록, 좋아요, 프로필 수정 시 로그가 DB에 저장되도록 구현
- 테이블명 : user_log
log 는 사용자의 액션이 기록됩니다
param_name 에는 사용자가 요청 시 넘겼던 파라미터 이름이 기록됩니다 (ex. DTO 클래스 이름)
param_value 에는 파라미터 value 가 기록됩니다. ( ex 프로필 수정 시 넘겼던 닉네임 값, 비밀번호 등이 기록 )
> Feat: AOP 로그 추적기 구현

- backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
- backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/MyPageInfoResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- backend/src/main/resources/import.sql
- frontend/src/api/modules/patchApi.js
- frontend/src/components/Modal/ChargePointModal.vue
- frontend/src/components/Modal/LinkAccountModal.vue
- frontend/src/views/MypageView.vue
- 계좌 연동 API 연동
- 포인트 충전 API 연동
- 포인트 환전 API 연동
https://github.com/EASYPEACH/shroop/assets/92674967/7e1c6e7c-2396-4bdf-8b1e-aba40a09453d
마이페이지에 들어왔을 때 OnBeforeMount로 유저의 정보를 조회할 때 계좌번호도 같이 가져오게 API를 수정하였고, 계좌번호 값이 null이면 계좌연동 버튼이 나타나게 했고, 만약 계좌 정보가 있으면 그 값이 나타나게 구현했습니다. 또한 계좌연동 버튼을 눌렀을 때 알러트 창이 나타나고 새로고침을 하여 다시 프로필 정보를 조회하게 했습니다. 
@Jiyun-Parkk  갓지윤
> Feat: 포인트 반영 API 프론트 연동 및 API 리팩토링

- backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
- frontend/src/App.vue
- frontend/src/store/useCheckLogin.js
다른 브라우저에서 로그인 시 로그인 페이지로 이동하도록 수정
notification 버튼이 이미 렌더링되어 있어 로그인 성공 여부를 나타내는 전역 변수를 제대로 못 가져오고 있는 것 같습니다
그래서 계속해서 로그인 여부 API 를 호출하고 있는 것으로 보입니다
-> 우선 403 에러시 프론트 페이지 새로고침 하도록 수정하였습니다
https://blog.sunimos.me/25
> Fix: 다른 브라우저에서 로그인 시, 500 에러가 나는 현상 수정

- backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
상품 전체 조회시 이미지는 대표이지미 하나만 가져오도록 수정했다.
> Bug: 상품 전체 조회시 이미지는 대표이지미 하나만 가져오도록 수정했다

- frontend/src/router/index.js
- frontend/src/views/auth/PhoneAuthView.vue
- frontend/src/views/mypage/MypageEditProfileView.vue
프로필 수정 후 빈값이 저장되어 이후에 기본이미지가 미노출 되었음 
(기본이미지는 빈값이 아닌 null 일때 나오도록 구현되어 있는 상태)
> Fix: 프로필 수정 시 이미지가 안나오는 현상 수정

- backend/src/main/java/com/easypeach/shroop/infra/s3/service/S3UploadService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
- backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
- S3 이미지 저장시 UUID를 붙여서 유니크한 이름으로 저장될 수 있도록 수정 => 동일한 이름의 이미지가 추가 저장이 안되는 이슈 수정
- 이미지 업데이트 할때 저장소의 이미지도 삭제되고 새로운 리스트로 저장될 수 있도록 수정
> Refactor: 이미지 저장시 유니크 이름으로 저장될 수 있도록 수정

- backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/LikeProductInfo.java
- backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
좋아요 응답 DTO 내부에서 카테고리 엔티티도 DTO로 수정하였음
마이페이지에서 좋아요 게시글 API 호출 시
좋아요 게시글 응답 DTO에 카테고리(엔티티)가 프록시 객체로 되어 있어서 JSON 직렬화가 불가능한 것으로 보임
해당 카테고리 엔티티도 DTO로 수정하였음
> Fix: 카테고리 엔티티를 DTO로 변경한다

- frontend/src/components/Banner/MypageProductBanner.vue
- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/components/ProductCard.vue
- frontend/src/main.js
- frontend/src/plugins/index.js
- 모바일 환경에서 배너가 다 보이지 않는 부분을 수정했습니다.
- 
[기존]
[변경]
> Refactor: 모바일 환경에서의 배너 크기 조정

- frontend/src/components/Button/HamburgerButton.vue
- frontend/src/components/Button/NotifyBellButton.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/plugins/vuetify.js
- frontend/src/store/modules/useShowNotify.js
- frontend/src/views/mypage/MypageHomeView.vue
- 모바일 환경에서 알림 버튼을 볼 수 있도록 ui 추가
- 알림 사이드바 활성상태에서 사이드 메뉴 열었을때, 알림 사이드바는 비활성화 되도록 수정
> Refactor: 모바일 환경에서 알림 버튼 추가

- backend/src/docs/asciidoc/transaction.adoc
- backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryController.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
- backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
- backend/src/main/resources/static/auth.html
- backend/src/main/resources/static/category.html
- backend/src/main/resources/static/delivery.html
- backend/src/main/resources/static/likes.html
- backend/src/main/resources/static/member.html
- backend/src/main/resources/static/notification.html
- backend/src/main/resources/static/product.html
- backend/src/main/resources/static/report.html
- backend/src/main/resources/static/return.html
- backend/src/main/resources/static/transaction.html
- backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryControllerTest.java
- frontend/index.html
- frontend/src/components/Banner/ProductBanner.vue
- frontend/src/views/mypage/MyPagePurchaseListView.vue
- frontend/src/views/mypage/MyPageSellListView.vue
- 기존에 전체 리스트를 불러왔던 구매내역 조회를 paging으로 구현했다
- 페이징으로 변경한 구매내역 조회 API를 프론트 코드에 적용시켰다
- 구매내역 조회의 테스트 코드를 수정했다
- 구매내역, 판매내역 조회의 URI를 수정했다
> Refactor: 마이페이지 구매내역 조회 페이징으로 리팩토링을 했다

- frontend/src/components/SideBar/NotifyBar.vue
알림 클릭시 이동하려는 페이지가 현재 위치일 경우 새로고침되도록 수정했다.
> Refactor: 알림 클릭시 페이지 이동 로직을 수정했다

- backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
- backend/src/test/java/com/easypeach/shroop/modules/member/domain/MemberTest.java
> Feat: 등급 점수 제한을 100점으로 제한한다

- backend/src/main/java/com/easypeach/shroop/modules/member/controller/PointController.java
- backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
- 포인트 충전/환전 로직을 한 트랙잭션으로 묶었다.
- 컨트롤러 단에서 돈의 차감/증감, 포인트의 차감/증감 총 두 번 서비스를 호출하는 식으로 로직이 구성되어 있다보니 한 트랜잭션에 묶이지 않은 상태여서 하나의 서비스를 호출하여 그 내부에서 두개의 처리를 진행하는 방식으로 변경하였습니다.
> Refactor: 포인트 리팩토링을 한다

- backend/src/main/java/com/easypeach/shroop/infra/aop/likes/RetryAspect.java
- backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
- backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
- backend/src/test/java/com/easypeach/shroop/concurrency/ProductConcurrencyTest.java
좋아요 테스트 후 상품 삭제하도록 수정
- 좋아요 재시도 로직에 에러 로그 출력하도록 추가
https://velog.io/@qwerty1434/JUnit%EC%9D%98-BeforeEach%EC%99%80-JPA%EB%A5%BC-MultiThread%EC%97%90%EC%84%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
> Refactor: 좋아요 테스트 후 상품 삭제하도록 수정

- frontend/src/components/CautionBlock.vue
- frontend/src/styles/global.style.css
- frontend/src/views/HomeView.vue
- frontend/src/views/product/ProductDetailsView.vue
> Refactor: 모바일 화면에서 구매하기 UI 틀어짐을 수정했다

- frontend/src/components/Modal/BuyerInfoModal.vue
구매자 정보보기 모달의 위치를 정상 위치로 수정했다
[수정 이전]
[수정 이후]
> Fix: 구매자 정보보기 모달 위치 수정
